name=ESPICs
version=0.5.0
author=Niklas
maintainer=Niklas
sentence=iCal parsing and calendar helper functions for ESP32.
paragraph=Pulls and Parses iCal events, filters upcoming events, and formats them for Arduino projects.
category=Communication
url=https://github.com/Niklas0511/ESPICs/tree/main
architectures=esp32